Updated tropical tree cover layer
Vizzuality/gfw pull request #4517
Opened 2023-03-02 13:31 UTC by SARodrigues

## Overview

TODO

## Tracking

[FLAG-698](https://gfw.atlassian.net/browse/FLAG-698)

2023-03-03 15:42 UTC, SARodrigues commented on services/datasets.js
> +      `/dataset?application=gfw&includes=metadata,vocabulary,layer&published=true&page[size]=9999&env=production,preproduction,staging${
This needs to be reverted before the PR is merged.

2023-03-03 15:42 UTC, SARodrigues commented on providers/datasets-provider/actions.js
> +    return ['preproduction', 'production', 'staging'].includes(env);
This needs to be reverted before the PR is merged.

2023-03-03 15:44 UTC, SARodrigues commented on components/map/components/legend/index.js
> -          dataset.layers = [newLayerKey];
This was the reason for the `state mutation detected between dispatches` error.

2023-03-14 13:01 UTC, pedrogpimenta requested changes
- [x] Also, a reminder to remove the forced env variables from the request :)

2023-03-14 13:17 UTC, SARodrigues commented on components/map/components/legend/component.jsx
> +                      toggle={isToggleLayer}
Good catch! You're right, it is not needed here; it'll be false inside the component. 
I'll remove it :)

2023-05-16 08:04 UTC, merged